### ISSUE TITLE
[Bug] - Auga: When sitting at main screen characters cycle

### ISSUE THREAD

**Issue by sbtoonz** [RandyKnapp/Auga#1]
Issue:
When coming to Fejd my characters visually cycle until I hit my selected character

Expectation:
When I select a character at the end of my player list
I expect to see this avatar immeiately

**Comment by RandyKnapp** [comment]
"Fixed" in release.

This cycling is generating character portrait images by taking screenshots. The players' hair is physics based, so it needs some frames to settle, that's why it does it. I shortened the settling time and for up to 5 or 6 players, it will be hidden by the fade in.
