### ISSUE TITLE
Does not work in the latest versions of Valheim.

### ISSUE THREAD

**Issue by StrikerOnLine** [RandyKnapp/Auga#126]
Does not work in the latest versions of Valheim.

**Comment by OwlCacone** [comment]
Just tried the mod, same thing happened. I even ran it solo without a single other mod enabled or even installed, just shows regular game UI. Other UI mods like Better UI do work

**Comment by uilson** [comment]
with the new Mistlands there are a couple things that need to be updated as some functions names changed , and a new eitr (magic stamina) bar needs to be added.

**Comment by RandyKnapp** [comment]
You guys gotta chill. I'll have a version of Auga out shortly

**Comment by uilson** [comment]
im chilling, i know how it goes, thats what i was telling the guys above me

**Comment by hamletmillqvist** [comment]
It appears to be working for me on latest version from thunderstore.
