### ISSUE TITLE
1.10 incompatible with Jewelcrafting

### ISSUE THREAD

**Issue by paague** [RandyKnapp/Auga#130]
Project Auga paired with Jewelcrafting is completely breaking the inventory interface. When interacting with a chest/crafting table it breaks to the point of needing to restart the game to turn off the inventory.

![Zrzut ekranu (83)](https://user-images.githubusercontent.com/117589753/206591542-7ccdb40e-b729-4d9c-a6da-6ef67714e901.png)
![Zrzut ekranu (82)](https://user-images.githubusercontent.com/117589753/206591546-273b3dd3-7709-497d-885d-10e6f28ed72c.png)

**Comment by Dorrivix** [comment]
I would like to see compatibility with the jewel crafting mod too. can't open my inventory when this and that mod are active.

**Comment by Vapok** [comment]
Yeah unfortunately the compatibility has to be built in from the Jewelcrafting side. Auga has an API that many other mods use. (See Recycle N Reclaim).

You would need to ask Smoothbrain to provide support within JC.
