### ISSUE TITLE
Mod Compatibility [Trash Items]

### ISSUE THREAD

**Issue by bjorno43** [RandyKnapp/Auga#14]
Mod name: Trash Items
Link: [NexusMods - Trash Items](https://www.nexusmods.com/valheim/mods/441)

**How the mod works**
Adds a new "tab" on the side of the original inventory menu. Dragging any items on top of it allows you to delete those items.

**Error(s)**
`[Error :Trash Items Mod] ac_text not found!`

**Comment by RandyKnapp** [comment]
This will be on the mod author to add this themselves using the Auga API, unfortunately.
