### ISSUE TITLE
Auga Not Working

### ISSUE THREAD

**Issue by Rain4549** [RandyKnapp/Auga#149]
![image](https://user-images.githubusercontent.com/100075665/211381498-8cfb9489-7423-47d4-8d62-99d0709c9170.png)
![image](https://user-images.githubusercontent.com/100075665/211381551-9f48c712-7e67-4cb2-9cee-3cf0a9971300.png)
![image](https://user-images.githubusercontent.com/100075665/211381596-1bd62b6c-5bcb-4ed4-910c-0af026b4a9e3.png)
Help Please

**Comment by RandyKnapp** [comment]
Auga is temporarily disabled for the main menu (except the settings menu). Your Auga appears to be working fine.

**Comment by Rain4549** [comment]
When is it activated?
