### ISSUE TITLE
Mod Compatibility [SimpleRecycling 0.0.13]

### ISSUE THREAD

**Issue by kiirdonel** [RandyKnapp/Auga#15]
**Mod Name:** [SimpleRecycling](https://valheim.thunderstore.io/package/abearcodes/SimpleRecycling/) by abearcodes

SimpleRecycling adds a button to chest inventories and a new tab to the workbench menu that allows you to uncraft items.

When used with Auga, there is no recycle tab in the workbench and the chest inventories don't open at all. Also, the repair button disappears from the workbench.

**Error(s):**
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ABearCodes.Valheim.SimpleRecycling.UI.StationRecyclingTabHolder.SetupTabButton () (at <53d5063764fa4559bad6a861499bd690>:0)
ABearCodes.Valheim.SimpleRecycling.UI.StationRecyclingTabHolder.EnsureRecyclingTabExists () (at <53d5063764fa4559bad6a861499bd690>:0)

[Error  : Unity Log] NullReferenceException
Stack trace:
ABearCodes.Valheim.SimpleRecycling.UI.ContainerRecyclingButtonHolder.SetupButton () (at <53d5063764fa4559bad6a861499bd690>:0)
ABearCodes.Valheim.SimpleRecycling.UI.ContainerRecyclingButtonHolder.EnsureRecyclingButtonExistsIfPossible () (at <53d5063764fa4559bad6a861499bd690>:0)
```

It's my first time submitting an issue like this so I hope I did it right, sorry if I didn't.

**Comment by RandyKnapp** [comment]
Thank you for this issue! Unfortunately, this will be on the mod developer to add this to their own mod using the Auga API.

**Comment by kiirdonel** [comment]
Okay, thank you! I'll let them know :)
