### ISSUE TITLE
not working correctly with "Extended Player Inventory"

### ISSUE THREAD

**Issue by LucTussi** [RandyKnapp/Auga#157]
hello i downloaded ur very very nice mod the UI/menues looks AWESOME

but it dont work correctly with "Extended Player Inventory" the extra armor- and quickslots r missing (look at screenshot link)
[https://www.nexusmods.com/valheim/mods/1356?tab=description](https://www.nexusmods.com/valheim/mods/1356?tab=description)

i hope u can fix that rly little problem

screenshots
[https://imgur.com/a/q9Be5sX](https://imgur.com/a/q9Be5sX)

**Comment by Vapok** [comment]
I don't know if we can get this working with the mod you linked, but if you use "Equipment and Quick Slots" by Randy Knapp, this will provide the functionality you're looking for and work with Auga.
