### ISSUE TITLE
Mod broken with new update

### ISSUE THREAD

**Issue by vitar0** [RandyKnapp/Auga#161]

**Comment by kurazarrh** [comment]
Bug needs description, but I can confirm. Even playing with no other mods loaded, version 1.1.3 causes my game to load me in as if I was floating over the ocean in a boat, and then even when it loads the correct area, the interface is all placeholder contents:

![20230317231223_1](https://user-images.githubusercontent.com/29897889/226081561-83ad1759-80dc-4f71-a328-74c7f9084f44.jpg)

![20230317231234_1](https://user-images.githubusercontent.com/29897889/226081562-59a0b5d3-5430-49e0-9967-d10277e84ed3.jpg)

**Comment by RandyKnapp** [comment]
Thanks! Yeah Auga is going to go on a little pause/hiatus until the UI
changes from the new versions of Valheim settle down.

**Comment by kurazarrh** [comment]
@RandyKnapp Ahh, that's a shame. Valheim's default interface is utter garbage to look at. Your mod makes everything really clean. I hope the changes settle down and you don't get burned out working on it!

**Comment by Vapok** [comment]
Please upgrade to version 1.2.2
