### ISSUE TITLE
Map icon names not working

### ISSUE THREAD

**Issue by PuNChLiNe9** [RandyKnapp/Auga#168]
![Screenshot 2023-04-01 205837](https://user-images.githubusercontent.com/129636420/229326945-9ccf6511-09f8-47c7-adef-19df16386bae.png)

Minor issue. Does not make it unusable, but does make it more difficult to figure out what is what. Loving the mod, it is absolutely outstanding! Keep up the good work!!

**Comment by Vapok** [comment]
Verified Bug... Added to the backlog.

**Comment by Vapok** [comment]
This is fixed in 1.2.3
