### ISSUE TITLE
v1.2.15 password-input allows just 1 character

### ISSUE THREAD

**Issue by patrulle** [RandyKnapp/Auga#202]
When connecting to a password-secured dedicated-server it is not possible to enter more than 1 character to join (v1.2.15).

![image](https://github.com/RandyKnapp/Auga/assets/142974507/2727233d-7555-41a1-a6eb-761dbdb44e9b)

**Comment by Vapok** [comment]
Known Input Issue that we are trying to Fix.

As a band aid fix (but also recommendation) Fast Link by Azumatt is an excellent tool, and allows you to skip having to enter passwords each time

**Comment by NHDriver4** [comment]
Thanks Vapok. I just found this mod the other day and I love it. Other than the password thing. I'll check out the Fast Link and start using Auga again. Cheers!

**Comment by Vapok** [comment]
This is fixed in 1.2.16
