### ISSUE TITLE
Focus taken away from InputField in custom UI

### ISSUE THREAD

**Issue by SpikeHimself** [RandyKnapp/Auga#205]
My mod XPortal uses a custom UI in which users can change the name of a portal (amongst other things).

I use `ActivateInputField()` to focus this InputField when the UI loads.

However I've been getting reports from users that, when they also have Auga installed, that focus is immediately taken away again.

Could you point me in the right direction of where/how Auga does this, so that I could think about fixes or work-arounds?

Relevant: https://github.com/SpikeHimself/XPortal/issues/69

**Comment by Vapok** [comment]
Hey Spike, this should be fixed in 1.2.16

**Comment by SpikeHimself** [comment]
Thank you @Vapok!
