### ISSUE TITLE
Incompatible with Current game patch

### ISSUE THREAD

**Issue by tobymaxgames** [RandyKnapp/Auga#213]
Today's Patch (patch 0.217.22) broken Auga. when starting the main menu has the console open with the "some text, some text, some text" spam, and menus don't look correct.

**Comment by worldendDominator** [comment]
Can confirm, though it also happens with other mods - EquipmentAndQuickSlots for me, don't know what else.

**Comment by oviron** [comment]
Can confirm, EpicLoot seems broken too

**Comment by OceanSnipe17** [comment]
Most other mods have updated and work now. Agua still not working throwing up the "Some Text" error when loading with it.

**Comment by worldendDominator** [comment]
Fixed now, please close.
