### ISSUE TITLE
Food and equipment slots overlayed {EquipmentandQuickSlots}

### ISSUE THREAD

**Issue by TheNakedMexican** [RandyKnapp/Auga#40]
I have the EquipmentAndQuickSlots mod, and the quickslots are overlayed on top of the food/stamina. Please see below:

![Equipment andquick slots](https://user-images.githubusercontent.com/89113542/129821469-e5ea699e-f7ff-40ed-b891-f5ab2ce78db3.png)

I have the following mods running through Overwolf ModManager:
BepInExPack_Valheim
ValheimPlus
Clock
FarmGrid
ExtendedItemDataFramework
EpicLoot
Better_Trader
EquipmentandQuickSlots
Veinmine
Jotunn
Hookgenpatcher
HoneyPlus
InstantMonsterLootDrop
Auga

How can I help fix this?

**Comment by RandyKnapp** [comment]
You can configure where the quickslots appear on the screen using the
Equipment and Quick Slots config file. I recommend `Quick Slots Position =
{"x":266.0,"y":220.0}`

**Comment by skol-pro** [comment]
Still not well position by default.. :-(
