### ISSUE TITLE
Using EquipmentAndQuickSlots Clips Health and Stam HUD

### ISSUE THREAD

**Issue by baruchvlz** [RandyKnapp/Auga#55]
![image](https://user-images.githubusercontent.com/14321495/134140637-ac4d95ae-c87f-4670-8925-eceb21d6a6a7.png)

**Comment by Wavebearer** [comment]
As a user of both mods, I recommend moving the Quick Slots icons using the configuration file. If you have Configuration Manager, you can adjust and preview it on the fly.

**Comment by srtzero** [comment]
Easy fix mate. Just edit the randyknapp.mods.equipmentandquickslots.cfg file. Look for the section called Quick Slots and replace the line 'Quick Slots Position = {"x":216.0,"y":150.0}' with 'Quick Slots Position = {"x":205.0,"y":68.0}' It place the quick slots below the stamina bar. See Pic. You can further customize it by editing the numerical values for the x, y axis.


![image](https://user-images.githubusercontent.com/38842965/134523041-1ba50d7f-4265-4927-a823-b1f27aeb58d4.png)

**Comment by baruchvlz** [comment]
Yea, didn't think about changing the position 🥇
