### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by SirOMGitsYOU** [RandyKnapp/Auga#66]
Get this message when launching with Auga and FPS Camera mod and RememberIPDammit! - https://hastebin.com/dimuqiripi.yaml

Mod also isn't active when loading up

**Comment by RandyKnapp** [comment]
This is Auga v 1.0.0, that's OLD. Get the latest from the Nexus,
Thunderstore, or here:
https://github.com/RandyKnapp/Auga/blob/main/Auga/AugaNexus.zip
