### ISSUE TITLE
 Mod Compatiblity [Jotunn v2.2.1] 

### ISSUE THREAD

**Issue by Digitalroot** [RandyKnapp/Auga#7]
https://www.nexusmods.com/valheim/mods/1138
https://github.com/Valheim-Modding/Jotunn
@sirskunkalot

NRE is thrown when settings is clicked on the main screen of Valheim. (FejdStartup)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Jotunn.GUI.InGameConfig.CreateModConfigTab () (at <ae3eb29e3d87405a8073e953faa4f05c>:0)
Jotunn.GUI.InGameConfig.FejdStartup_OnButtonSettings (On.FejdStartup+orig_OnButtonSettings orig, FejdStartup self) (at <ae3eb29e3d87405a8073e953faa4f05c>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<FejdStartup::OnButtonSettings>?-1410220800(FejdStartup)
UnityEngine.Events.InvokableCall.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <30e538f3cf5548cfa6abc9730778bcef>:0)
UnityEngine.UI.Button.Press () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by RandyKnapp** [comment]
Oof, unfortunately the tabs are not in the same hierarchy as vanilla, this will be a "no fix"

**Comment by sirskunkalot** [comment]
I will at least make it NRE proof. But I won't write workarounds for mods that replace the GOs from vanilla. If I start that for one mod, Pandora's Box is opened wide ;)

It's the same with custom KeyHints. But I guess I cannot probe that stuff reliably to make it fit all future GUI overhauls.

And same with custom piece table categories, too. Those are kind of a bummer, though. I do respect the vanilla style 100% and just add to that. But the GO is replaced there, too.
