### ISSUE TITLE
Epic Loot / Auga / bounties 

### ISSUE THREAD

**Issue by Funky18229** [RandyKnapp/Auga#71]
Randy Auga  has many conflicts with your own mod , epicloot adventures  ....u get a error about mini map and then when u load into game and get a bounty  or  a treasure map , it will spam epiclootadventures null ref.   When you do not install, Auga........everything works You also can not put any pins on the map not do any maps or bounties show up on map. 

This has been a issue since the new update. PLEASE take the time to  fix this?  Auga is not usable due to this. 
Do you not test these mods to work with your own mods?  /smile Its just I spent many hours trying to figure this out.  A waste of time

**Comment by RandyKnapp** [comment]
Ah! I'm so glad that you're an expert in testing mods! Well, here's the link to the EpicLoot repo, just fork these repos, figure out what's wrong, and make a PR with the fix. Let me know when you're done, thanks!

**Comment by RandyKnapp** [comment]
https://github.com/RandyKnapp/ValheimMods
