### ISSUE TITLE
[Issue] Settings: Set a key hangs

### ISSUE THREAD

**Issue by 4Magma** [RandyKnapp/Auga#77]
Tried to erase a key in settings. I see "Press a Key" but nothing happens.
Can't close, set or erase? (L key is used for switch running and lock/unlock
from Precise Piece Placement)

Tested 2 times, first in world, second in main screen.

1. I have time mod and could pause/unpause the game behind
2. to check if its a inworld problem, but froze again

- all mod versions should be up to date.
- have only updated Jotunn between both tries.

**Comment by RandyKnapp** [comment]
Fixed in 1.0.8
