### ISSUE TITLE
Mod Compatiblity [Better Wards v1.5.4]

### ISSUE THREAD

**Issue by Digitalroot** [RandyKnapp/Auga#8]
https://www.nexusmods.com/valheim/mods/402
@AzumattDev

NRE is thrown when loading into a world, SP, no server running.

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.EventSystems.UIBehaviour.IsActive () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.SetVerticesDirty () (at <5abdc278a459476dabe36f8ad65ea091>:0)
(wrapper dynamic-method) UnityEngine.UI.Text.DMD<UnityEngine.UI.Text::set_text>(UnityEngine.UI.Text,string)
Chat.UpdateChat () (at <1b865f8b3455488592cdc401081112e3>:0)
Chat.AddString (System.String text) (at <1b865f8b3455488592cdc401081112e3>:0)
(wrapper dynamic-method) SMT.(object,string)
SMT.UM (System.Object , System.String , SMT ) (at <ad65e31c6fb146a7869be54f79294961>:0)
BetterWards.PatchClasses.ChatPatchAwake.Postfix (Chat& __instance) (at <ad65e31c6fb146a7869be54f79294961>:0)
(wrapper dynamic-method) Chat.DMD<Chat::Awake>(Chat)
UnityEngine.Object:Instantiate(GameObject, Transform)
InstantiatePrefab:Awake()

**Comment by AzumattDev** [comment]
It might be how I chose to add it to the chat.

**Comment by AzumattDev** [comment]
This is fixed. You can close the issue.
